services:
  - type: web
    name: pvpmod-site
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_KEY
        sync: false
      - key: LAUNCHER_URL
        sync: false
      - key: DATA_DIR
        value: /opt/render/project/src/data
    disk:
      name: pvpmod-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1
